set -g pane-border-style fg=white
set -g pane-active-border-style "bg=default fg=cyan"

# remap prefix from 'Ctrl-b' to 'Ctrl-s'

unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

bind r source-file ~/.tmux.conf
