# Styling
set -g status-position top
set -g status-style fg="brightPurple",bg=default

if '[ "$TERM" != "#{default-terminal}" ]' {
  if -F '#{!=:#{status},2}' {
      set -Fg 'status-format[0]' '#{status-format[0]}'
      set -g 'status-format[1]' ''
      set -g status 2
  }
}

set -g status-left-length 40

set -g status-right-length 40
set -g status-right "#[fg=brightPurple,bg=default]%d-%m-%Y %H:%M:%S#[default]"
set -g status-interval 1

set -g window-status-format "  #I:#W  "
set -g window-status-current-format "#[fg=blue,bg=default]\uf432 #I:#W \uf434#[default]"

set -g pane-border-style fg=white
set -g pane-active-border-style "bg=default fg=blue"

# Global Settings
set -g mouse on

# Bindings
## Prefix
unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix
## Reload (Source)
bind r source-file ~/.tmux.conf \; display "Reloaded"
